# Lecture 1 - Programming 

## What we are going to cover today

### Fundamentals of programming. How does a computer actually run software? What are the basic operations of programming?
- Data structures - variables, lists, arrays/matrixes, data frames, objects.
- The four fundamental operations a computer does:
    1. Arithmetic
    2. Assignment
    3. Decision
    4. Looping
- How do they work in R. What abstractions are used to make our life easier (or harder) in R. Vectorization and functions.

### Fundamentals of data management. How do we work with datasets? How do we load data, save data, and _wrangle_ with data?

# 1. Prerequisites

First things first!

**It's a good idea to comment your code!**

All lines starting with 

### Loading packages and setting up the environment.

R contains modules that add fuctionalities to R called packages. 

You can install packages directly in R like this. You only need to do this step **once**. However, there is **nothing wrong** if you install packages each time you run your script. It may just ve slow: 

In [35]:
#install.packages('ggplot2')
#install.packages('tidyverse')
#install.packages("readxl")

**Remember you always need to load packages before using them**. 

In [76]:
library('ggplot2')
library('tidyverse')

── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──
✔ tibble  1.4.2     ✔ purrr   0.2.5
✔ tidyr   0.8.1     ✔ dplyr   0.7.6
✔ readr   1.1.1     ✔ stringr 1.3.1
✔ tibble  1.4.2     ✔ forcats 0.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()


Also note, sometimes, packages conflict with other packages, as they contain functions that are identical in name. One frequent example is **plyr** and **dplyr**. 

You can either choose to either use one package only, or you can call the desired function explicitly (using "explicit namespacing") using **package::function**. If R includes it by default, use **base::** as the package name (namespace)

In [3]:
a=c(10,25,50)

base::sum(a)
sum(a)

[1] 85

[1] 85

# 2. Data structures and data

### A variable is an object storing data:

In [87]:

integer_var = 1
float_var = 1.5
nothing_var = NA
string_var = 'This is a string'
boolean_var = TRUE

# And we can do operations

integer_var + float_var
integer_var - float_var
integer_var * float_var
integer_var / float_var
integer_var == float_var
integer_var == 1
integer_var > float_var


[1] 2.5

[1] -0.5

[1] 1.5

[1] 0.6666667

[1] FALSE

[1] TRUE

[1] FALSE

# R is vectorial. 

## This means:

### we can store not only numbers, but also vectors and matrixes (collections of numbers)
### we can compute not only number additions, but also addition and multiplication of vectors and matrixes. All operations that work on numbers extend on  vectors and matrixes

So, for example:

## Vectors

### Vectors are lists of numbers.

In [89]:
X <- c(1,2,3,4,5)
Y <- c(10,20,30,40,50)
Z = c(X,Y)

### `c(elements)` makes vectors

In [91]:
X
Y
Z
c(Z,1)

[1] 1 2 3 4 5

[1] 10 20 30 40 50

[1]  1  2  3  4  5 10 20 30 40 50

[1]  1  2  3  4  5 10 20 30 40 50  1

#### And `:` makes sequences. 
`1:5 == c(1,2,3,4,5)`  

In [164]:
seq_a=1:5
seq_b=c(1,2,3,4,5)
seq_a
seq_b
seq_a == seq_b

[1] 1 2 3 4 5

[1] 1 2 3 4 5

[1] TRUE TRUE TRUE TRUE TRUE

#### The size is given by length.


In [98]:
length(X)
length(Y)
length(Z)

[1] 5

[1] 5

[1] 10

#### And to get the n'th element, just do `VECTOR[element]` 
#### In R, the first element is 1

### The `[element]` in a vector is called an index

In [108]:
X[1]
Y[3]

[1] 1

[1] 30

[1] 1 2 3 4 5

[1] 1 2 3

[1] 2 3 4 5

#### And you can partition using :


In [113]:
X
Y[1:3]
X[-1]

[1] 1 2 3 4 5

[1] 10 20 30

[1] 2 3 4 5

### All operations are vectorial, thus, work on vectors automatically

In [15]:
X+Y

[1] 11 22 33 44 55

In [16]:
X*Y

[1]  10  40  90 160 250

In [19]:
Y-X

[1]  9 18 27 36 45

In [47]:
X%*%Y

[,1]
[1,] 550

### In statistics, X*Y is refered to as an interaction between X and Y

## Matrixes

### Matrixes are vectors of identical vectors, 2-dimensional tables of numbers

In [118]:
column_1 = c(1,2,3)
column_2 = c(2,9,20)
column_3 = c(10,20,30)
matrix_m = matrix(c(column_1,column_2,column_3),nrow=3,ncol=3)
matrix_m

[,1] [,2] [,3]
[1,] 1     2   10  
[2,] 2     9   20  
[3,] 3    20   30

#### We use `matrix_m[ROW, COLUMN]` to point to individual values
#### `matrix_m[ROW, ]` returns a whole row
#### `matrix_m[,COLUMN ]` returns a whole column

In [141]:
matrix_m[1,3]

[1] 10

In [142]:
matrix_m[3,]

[1]  3 20 30

In [143]:
matrix_m[,2]

[1]  2  9 20

You can even specify a vector of columns and rows to return!

In [288]:
matrix_m[c(1,2),]

[,1] [,2] [,3]
[1,] 1    2    10  
[2,] 2    9    20

In [151]:
matrix_m[c(1,2),c(1,3)]

[,1] [,2]
[1,] 1    10  
[2,] 2    20

### Data Frames and Tibbles

### Dataframes are matrixes where:

#### 1. Columns can be heterogenous - i.e. each column can be of a different type
#### 2. Columns have names.

### Tibbles are a slightly improved version of data-frames. They can easily be converted between each other, and this generally happens without you knowing
### We will call both data-frames and tibbles tables in this tutorial

In [295]:
country = c('Afghanistan','Pakistan','India','Uzbekistan')
gdp = c(2452,7932,6932,9201)
battles = c(64,81,12,20)
asia_fighting = data.frame(country=country, gdp=gdp, battles=battles)
asia_fighting

country     gdp  battles
1 Afghanistan 2452 64     
2 Pakistan    7932 81     
3 India       6932 12     
4 Uzbekistan  9201 20

In [321]:
## Indexing with a single [] will return a data frame IF POSSIBLE.
## ONE INDEX RETURNS THE COLUMN
asia_fighting['gdp']

## TWO INDEXES ARE ALWAYS row, column:
# First row:
asia_fighting[1,]

# First two rows:
asia_fighting[c(1,2),]

# First and third column
asia_fighting[,c(1,3)]

# Only GDP and Battles for third row
asia_fighting[3,c(2,3)]

# Only GDP and Battles for Uzbekistan
asia_fighting['country'=='Uzbekistan']

gdp 
1 2452
2 7932
3 6932
4 9201

country     gdp  battles
1 Afghanistan 2452 64

country     gdp  battles
1 Afghanistan 2452 64     
2 Pakistan    7932 81

country     battles
1 Afghanistan 64     
2 Pakistan    81     
3 India       12     
4 Uzbekistan  20

gdp  battles
3 6932 12

1
2
3
4

Calling with only ONE `[..]` will return a data frame if possible:

Always call with TWO `[[...]]` to return a vector or a scalar (single-value) number. However, it must ONLY return 1 column OR 1 row OR 1 value!

In [343]:
asia_fighting['gdp']
asia_fighting[['gdp']]
asia_fighting$gdp

gdp 
1 2452
2 7932
3 6932
4 9201

[1] 2452 7932 6932 9201

[1] 2452 7932 6932 9201

In [344]:
asia_fighting[[2,2]]


[1] 7932

## EXTRABITS : LISTS!

### Lists are vectors of heterogenous vectors

In [167]:
list_1 <- list(
  1:3, 
  "a", 
  c(TRUE, FALSE, TRUE), 
  c(2.3, 5.9)
)list_1
list_1

[[1]]
[1] 1 2 3

[[2]]
[1] "a"

[[3]]
[1]  TRUE FALSE  TRUE

[[4]]
[1] 2.3 5.9

In [170]:
list_1[1]

[[1]]
[1] 1 2 3

## EXTRABITS : MATRIX OPERATIONS!

Operations also work on matrixes, as matrixes are also vectors!

In [41]:
X = c(1,2,-1)
Y = matrix(c(10,20,30,40,50,60), nrow=3, ncol=2)

X
Y

[1]  1  2 -1

[,1] [,2]
[1,] 10   40  
[2,] 20   50  
[3,] 30   60

In [42]:
X*Y

[,1] [,2]
[1,]  10   40 
[2,]  40  100 
[3,] -30  -60

In [45]:
X%*%Y

[,1] [,2]
[1,] 20   80

In [28]:
X = matrix(c(1,2,3,4), nrow=2, ncol=2)
Y = matrix(c(5,10,50,100), nrow=2, ncol=2)

print('X:')
X

print('Y:')
Y

[1] "X:"


[,1] [,2]
[1,] 1    3   
[2,] 2    4

[1] "Y:"


[,1] [,2]
[1,]  5    50 
[2,] 10   100

In [33]:
print("X+Y:")
X+Y


[1] "X+Y:"


[,1] [,2]
[1,]  6    53 
[2,] 12   104

In [39]:
print ("Do you remember your highschool algebra?") 
print("X*Y does the element :")
X*Y
X%*%Y

[1] "Do you remember your highschool algebra?"
[1] "X*Y does the element :"


[,1] [,2]
[1,]  5   150 
[2,] 20   400

[,1] [,2]
[1,] 35   350 
[2,] 50   500

# 3. Basic Programming technique

#### Programming means making a machine think.
#### Thinking (in this context) three things:

  1. Calculate stuff (e.g. 4*2, 2+10, mean(x), sd(y)). By calculate we mean simple stuff (addition, subtraction, division, multiplication and simple logic, i.e. AND, OR, NOT)!. This is called in CS-lingo "arithmetic".
  2. Store results in memory, and retrieve them for later use. This is called "assignment".
  2. make decisions (given some alternatives, pick 1, or more). This is called "logic".

#### And computers can only make TWO kinds of decisions:
  1. Choose, based on some logic, between doing something or something else. This is called "branching"
  2. Choose, based on some logic, to repeat an action a number of times (or until a condition is met). This is called "looping".
  All these decisions do one thing and one thing only - change the way the program is run (i.e. the program flow)

#### So all in all, a computer can only do four things <font color="red"><u>Arithmetic, Assignment, Branch, Loop</u></font>

EXTRA BIT: This can actually be reduced further - as computers actually do even less. How far can we go?


## Program Flow

![flow](img/pf_run.png)

![if](img/pf_if.png)

In [49]:
a <-64
#a <- -10
if (a>0) 
{
  print (sqrt(a))
} else {
  print ("I can't compute a square root of a negative number!")
}

[1] 8


![for](img/pf_for.png)

In [59]:
x <- 0
for (i in 1:5)
    {
    x <- x + 2^i
    print('******')
    print(i)
    print(x)
    }
print("DoneLoop")
x = x*10
print(x)

[1] "******"
[1] 1
[1] 2
[1] "******"
[1] 2
[1] 6
[1] "******"
[1] 3
[1] 14
[1] "******"
[1] 4
[1] 30
[1] "******"
[1] 5
[1] 62
[1] "DoneLoop"
[1] 620


![for](img/pf_for2.png)

In [60]:
vect = c(2,5,10,3)
x <- 0
for (i in vect)
    {
    x <- x + 2^i
    print('******')
    print(i)
    print(x)
    }
print("DoneLoop")
x = x*10
print(x)

[1] "******"
[1] 2
[1] 4
[1] "******"
[1] 5
[1] 36
[1] "******"
[1] 10
[1] 1060
[1] "******"
[1] 3
[1] 1068
[1] "DoneLoop"
[1] 10680


![for](img/pf_forfor.png)

In [171]:
a=matrix(c(1,2,3,-10,20,+30,15,-30,45,10,100,100),nrow=4, ncol=3)
a
nrow(a)
ncol(a)

for (i in 1:nrow(a)) 
{
    for (j in 1:ncol(a))
     {
         print (a[i,j])
     }
}

[,1] [,2] [,3]
[1,]   1   20   45 
[2,]   2   30   10 
[3,]   3   15  100 
[4,] -10  -30  100

[1] 4

[1] 3

[1] 1
[1] 20
[1] 45
[1] 2
[1] 30
[1] 10
[1] 3
[1] 15
[1] 100
[1] -10
[1] -30
[1] 100


## Functions

![func](img/pf_func.png)

#Anything looking like `XXXX(stuff)` is a function call!

`glm(y~X)` is a function call to the function `glm`. Thus, we don't need to write all the code doing regression each time we want to do a regression!

In [373]:
last_day_in_month <- function (month)
  { 
    months = c(31,28,31,30,31,30,31,31,30,30,30,31)
    return (months[month]) 
  }

last_day_in_month(3)
last_day_in_month(2)

[1] 31

[1] 28

In [374]:
battles_by_month <- data.frame(battles=c(31,28,63,62,11,32,53,2), month=c(1,2,2,3,5,6,2,3), battles_by_day=NA)
battles_by_month

for (i in 1:nrow(battles_by_month))
{
  battles_by_month[i,'battles_by_day'] <- battles_by_month[i,'battles']/last_day_in_month(battles_by_month[i,'month'])
}
battles_by_month

battles month battles_by_day
1 31      1     NA            
2 28      2     NA            
3 63      2     NA            
4 62      3     NA            
5 11      5     NA            
6 32      6     NA            
7 53      2     NA            
8  2      3     NA

battles month battles_by_day
1 31      1     1.00000000    
2 28      2     1.00000000    
3 63      2     2.25000000    
4 62      3     2.00000000    
5 11      5     0.35483871    
6 32      6     1.06666667    
7 53      2     1.89285714    
8  2      3     0.06451613

In [388]:
## Let's walk you through some of the code

reps <- 1000 # Set the number of repetitions at the top of the script
par.est <- matrix(NA, nrow = reps, ncol = 4) # Empty matrix to store the
# estimates 
b0 <- .2 # True value for the intercept
b1 <- .5 # True value for the slope
n <- 1000 # Sample size
X <- runif(n, -1, 1) # Create a sample of n observations on the 
# independent variable X

for(i in 1:reps){ # Start the loop
  Y <- b0 + b1*X + rnorm(n, 0, 1) # The true DGP, with N(0, 1) error
  model <- lm(Y ~ X) # Estimate OLS model
  vcv <- vcov(model) # Variance-covariance matrix
  par.est[i, 1] <- model$coef[1] # Put the estimate for the intercept
  # in the first column
  par.est[i, 2] <- model$coef[2] # Put the estimate for the coefficient on
  # X in the second column
  par.est[i, 3] <- sqrt(diag(vcv)[1]) # SE of the intercept
  par.est[i, 4] <- sqrt(diag(vcv)[2]) # SE of the coefficient on X
} # End the loop

# Coefficients
# Absolute Bias
ab.beta0 <- mean(abs(par.est[ , 1] - b0))
ab.beta1 <- mean(abs(par.est[ , 2] - b1)) 

print('ab.beta1')
ab.beta1

# MSE
mse.beta0 <- mean((par.est[ , 1] - b0)^2)
mse.beta1 <- mean((par.est[ , 2] - b1)^2)

print('mse.beta1')
mse.beta1

# Standard Errors
# Standard Deviation
sd.beta0 <- sd(par.est[ , 1]) # SD of the intercept estimates
mean.se.beta0 <- mean(par.est[ , 3]) # Mean SE of the intercept

sd.beta1 <- sd(par.est[ , 2]) # SD of the coefficient on X estimates
mean.se.beta1 <- mean(par.est[ , 4]) # Mean SE of the coefficient on X

print('sd.beta1')
sd.beta1

print('mean.se.beta1')
mean.se.beta1

[1] "ab.beta1"


[1] 0.04388291

[1] "mse.beta1"


[1] 0.003084587

[1] "sd.beta1"


[1] 0.05555863

[1] "mean.se.beta1"


[1] 0.05524295

In [389]:
runif(1, -1, 1)
# THIS IS A FUNCTION DRAWING RANDOM NUMBERS
# first argument = how many
# second argument = from where
# third argument = to where
# other functions are plot(), glm()...

[1] 0.887135

In [384]:
runif(2, -1, 1)

[1] -0.8065867  0.2263959

Perhaps runif looks like this: 

`runif <- function(how_many, from_where, to_where)
  {
  out_vector <- c()
  for (i in 1:n)
     {
     out_number <- pull_from_magic_hat_with()
     out_vector <- c(out_vector,out_number)
     }
  return(out_vector)
  }`
  
And if you are curious what the `pull_from_magic_hat_with()` is and how it looks, talk to me in the break.

## BREAK

## EXTRABITS:

### I want to know more about loops!!!

##### Then, listen to Prof. Brailsford talk about loops, and explain another concept, which we won't go into, called recursion.

https://www.youtube.com/watch?v=HXNhEYqFo0o


### I heard loops are bad and horrible and horrendous and I shouldn't use them

##### <font color = red> Nope, they are not. </font>

Loops are how the computer is working internally at the processor level. There is actually a physical device on the CPU called an instruction counter to store the `i` in the `for (i in ...)`. 

The problem is R doesn't use that. It runs many layers of abstractions above that, which, due to some very technical bits, make expanding vectors and matrixes very, very, very slow. 

Take for example this code generating 10000 sets of random draws from the normal distribution:

In [236]:
library(tictoc)
tic('slow:')
m <- matrix(nrow=100)

tic()
out <- matrix()
for (i in 1:10000) {
    column <- runif(100,0,1)
    m <- cbind(m,column)
    }
toc()
m[10:20,2:3]

slow:: 28.569 sec elapsed


column    column    
 [1,] 0.9511705 0.84901587
 [2,] 0.6303969 0.68335068
 [3,] 0.8671169 0.05483491
 [4,] 0.9405014 0.03518542
 [5,] 0.1157129 0.41427004
 [6,] 0.2066271 0.28363345
 [7,] 0.5634485 0.11892980
 [8,] 0.1926335 0.99680480
 [9,] 0.4382140 0.03008671
[10,] 0.4306146 0.28106444
[11,] 0.9263096 0.29025703

You can fix this by simply pre-assigning the matrix with NA when you start your code, and filling it in place

In [239]:
library(tictoc)
tic('fast:')
m <- matrix(nrow=100, ncol=10000)

tic()
out <- matrix()
for (i in 1:10000) {
    column <- runif(100,0,1)
    m[,i] <- column
    }
toc()
m[10:20,2:3]

fast:: 0.073 sec elapsed


[,1]       [,2]      
 [1,] 0.93069128 0.30938609
 [2,] 0.03482239 0.23800325
 [3,] 0.44239428 0.96276076
 [4,] 0.91654117 0.80615751
 [5,] 0.23564680 0.10999191
 [6,] 0.92934034 0.97331096
 [7,] 0.08262005 0.06597795
 [8,] 0.65446278 0.55803567
 [9,] 0.15664704 0.60897247
[10,] 0.36942165 0.24724355
[11,] 0.88493434 0.84415599

It is not the loop that is slow, that's fast.
It is the matrix expansion!

`Apply()`, `rapply()`, `sapply()` are functions looping without writing for-loops. This is called "functional programming" and is rather hard to grasp your head around. So hard in fact, most programmers think it's unintuitive and problematic for more than very simple one-liners - being a very complex mathematical abstaction.

If you feel comfortable with applys, use them, otherwise, for loops are "mainstream" in most languages -- less than 1% of code globally is written in functional form

In [346]:
small_data_frame=data.frame(x=c(1:10),b=c(2,4,6,8,10,12,14,16,18,20))
small_data_frame

lapply(small_data_frame,mean)

for (column in colnames(small_data_frame))
    {
    print(column)
    print(mean(small_data_frame[[column]]))
    }

x  b 
1   1  2
2   2  4
3   3  6
4   4  8
5   5 10
6   6 12
7   7 14
8   8 16
9   9 18
10 10 20

$x
[1] 5.5

$b
[1] 11

[1] "x"
[1] 5.5
[1] "b"
[1] 11


# 4. Data Management

## What is data management?

**It is gathering and manipulating data from a raw format to a format that suits your analytic tasks**.

It consists of the following processes:

1. **Filtering** - selecting only the information you need from the whole dataset; This entails filtering observations (e.g. only countries in Africa) and columns (e.g. only countries in Africa)
1. **Aggregation** - changing the unit of analysis to a coarser level;
1. **Disaggregation** - breaking down a coarse-level dataset to a finer level;
1. **Joining** -- Bringing together multiple datasets containing different kinds of observations for the same units (e.g. make one dataset from two datasets of countries, one containing GDP information and one containing conflict information);
1. **Union** -- "Glueing" together observations from two datasets having the same structures but different units
1. **Transforms** -- Changing data to suit your needs (recode, create derived measures etc.)


We are going to use a **language** for data management called **dplyr**. It's an extension to R, works well with base R, but makes life easy and allows good management to happen.

## **Filtering**
![Filtering](img/dm_fil.png)

### We filter using the following functions

#### For columns:

`select(dataframe, c(ROWS WE WANT))`

Example `select(dataframe, c(country, gdp))`

#### For rows: 

`filter(dataframe, CONDITION)`

Example `filter(dataframe, gdp<10000)`
Available operators are `< > <= >= == is.na() !in.na() %in%`


`sample_frac(dataframe, PERC)`
`sample_n(dataframe, N)`

## **Aggregation**
![Filtering](img/dm_group.png)

## We do this in two steps!

`grouped_table = group_by(table, VARIABLES WE WANT TO GROUP BY)`
`summarized = summarize(grouped_table, variable = FUNCTION(column))`

There are many functions you can use:
`n(), sum(), avg(), median(), sd(), min(), max()`

# If you want only to eliminate duplicates from your dataset

You could very well do something like

`grouped_table = group_by(table, ALL VARIABLES)`

`eliminated = summarize(group table, new_var1 = max(var1) ...)`

But there are some helper functions so that you don't waste time when you have a lot of columns:

`distinct(table)`

AND

`summarize_all()`

## **Disaggregation**
![Filtering](img/dm_diss.png)


## **Joining**
![Filtering](img/dm_join.png)

## **Inner Joins**
![Filtering](img/dm_join_inner.png)

### Inner joins will only keep those observations that exist in BOTH table A and table B. This is the default behavior in almost all langages (`base R, dplyr, SQL, Pandas`).

#### Thus, ALWAYS be careful when joining not to lose observations by mistakes when you still need them

## **Left Joins**
![Filtering](img/dm_join_left.png)

### Left joins will only keep the structure of the LEFT table (table A). 

#### This allows you to carry a table-structure from the beginning of your data management work to the end, and take care of your NAs (missing observations) at the end of the work.

## **Right Joins**
![Filtering](img/dm_join_right.png)

### Right joins will only keep the structure of the RIGHT table (table B). 

#### Order thus matters. A x B is NOT B x A!

## **Outer Joins**
![Filtering](img/dm_join_outer.png)

### Outer joins will keep all observations in BOTH A AND B

#### Always check how your matching variable looks! Sometimes, in places like SQL, you have to specify to keep both the matching variables present in A and B, otherwise you may end up with NAs in the resulting table.

## Transform

![Filtering](img/dm_lag.png)

# THERE'S AN ORDER TO OPERATIONS

### 1. EXPLORE
### 2. PLAN
### 3. FILTER
### 4. AGGREGATE
### 5. UNION
### 6. JOIN


### If you need to x. TRANSFORM DATA, put this step in the dataset that has the FEWEST observations

Why do we do this? For performance!



## We need a task

#### Task : I want to know whether there is a relationship between GDP growth and the number of conflicts in Sub-Saharan Africa between 2015 and 2018


### Let's first load some data

In [77]:
conflict = read_csv('https://raw.githubusercontent.com/mihaicroicu/AQMLecture1/master/Data/aqm1_conflict.csv')
country = read_csv('https://raw.githubusercontent.com/mihaicroicu/AQMLecture1/master/Data/aqm1_country.csv')

Parsed with column specification:
cols(
  conflict_id = col_integer(),
  year = col_integer(),
  country = col_character(),
  country_id = col_integer(),
  side_a = col_character(),
  side_a_id = col_integer(),
  side_b = col_character(),
  side_b_id = col_character(),
  fatalities = col_integer(),
  type_of_conflict = col_character(),
  incompatibility = col_integer(),
  territory_name = col_character()
)
Parsed with column specification:
cols(
  country_name = col_character(),
  cid = col_integer(),
  country_id = col_integer(),
  year = col_integer(),
  proportion_educated = col_double(),
  gdp = col_double(),
  population = col_integer()
)


## We can look at the data in various ways

### Look at a few rows

  

In [78]:
head(country)

country_name cid country_id year proportion_educated gdp     population
1 Cape Verde   40  402        2010 0.284               1502.29 496       
2 Cape Verde   40  402        2011 0.289               1509.93 499       
3 Cape Verde   40  402        2012 0.293               1407.29 503       
4 Cape Verde   40  402        2013 0.298               1492.12 506       
5 Cape Verde   40  402        2014 0.303               1509.10 510       
6 Cape Verde   40  402        2015 0.308               1513.00 513

In [79]:
head(conflict)

conflict_id year country          country_id side_a                        
1 283         2016 DR Congo (Zaire) 490        Government of DR Congo (Zaire)
2 283         2017 DR Congo (Zaire) 490        Government of DR Congo (Zaire)
3 287         2015 Burundi          516        Government of Burundi         
4 297         2016 Nigeria          475        Government of Nigeria         
5 297         2017 Nigeria          475        Government of Nigeria         
6 297         2015 Nigeria          475        Government of Nigeria         
  side_a_id side_b                                               
1 89        Kamuina Nsapu                                        
2 89        CMC, CNPSC (Yakutumba), Kamuina Nsapu, M23, MNR      
3 93        FPB, Military faction (forces of Godefroid Niyombare)
4 84        Jama'atu Ahlis Sunna Lidda'awati wal-Jihad           
5 84        Jama'atu Ahlis Sunna Lidda'awati wal-Jihad           
6 84        Jama'atu Ahlis Sunna Lidda'awati wal-Jihad           
  side_b_id                    fatalities type_of_conflict incompatibility
1 6590                          164       3                2              
2 1160, 3043, 6590, 6740, 6920 1608       3                2              
3 6187, 6297                    133       3                2              
4 1051                          162       4                2              
5 1051                         1062       4                2              
6 1051                         2703       4                2              
  territory_name
1 NA            
2 NA            
3 NA            
4 NA            
5 NA            
6 NA

### And find out a little bit about the type of data in the dataset

In [51]:
str(country)

Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	416 obs. of  7 variables:
 $ country_name       : chr  "Cape Verde" "Cape Verde" "Cape Verde" "Cape Verde" ...
 $ cid                : int  40 40 40 40 40 40 40 40 41 41 ...
 $ country_id         : int  402 402 402 402 402 402 402 402 437 437 ...
 $ year               : int  2010 2011 2012 2013 2014 2015 2016 2017 2010 2011 ...
 $ proportion_educated: num  0.284 0.289 0.293 0.298 0.303 0.308 0.315 0.322 0.214 0.222 ...
 $ gdp                : num  1502 1510 1407 1492 1509 ...
 $ population         : int  496 499 503 506 510 513 516 519 19738 20120 ...
 - attr(*, "spec")=List of 2
  ..$ cols   :List of 7
  .. ..$ country_name       : list()
  .. .. ..- attr(*, "class")= chr  "collector_character" "collector"
  .. ..$ cid                : list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  .. ..$ country_id         : list()
  .. .. ..- attr(*, "class")= chr  "collector_integer" "collector"
  .. ..$ year               : lis

### Let's check the temporal and spatial extent of the data.

Let's do this it like this.
1. We first take out the year column from the data.
2. We then only keep distinct observations so that we get 2015, 2016, 2017 and not 2015, 2015, 2015, 2015, 2015,...
3. We sort it, so that we don't get 2010, 2015, 2014, 2016

We do this using the **dplyr** `distinct()` function which returns deduplicated items

In [14]:
# First, filter
extent <- select(country, year) 

# Then, aggregate We use distinct, because we only need a distinct copy!
extent <- distinct(extent, year)

# And then we sort and prepare the data
extent <- arrange(extent, year)

# And then we print the output
#
extent

year
1 2010
2 2011
3 2012
4 2013
5 2014
6 2015
7 2016
8 2017

### Or, we can chain this with pipes.

In [15]:
country %>% select(year) %>% distinct(year) %>% arrange(year)

year
1 2010
2 2011
3 2012
4 2013
5 2014
6 2015
7 2016
8 2017

In [69]:
distinct(country['country_name'])
distinct(conflict['country'])

country_name            
1  Cape Verde              
2  Cote d'Ivoire           
3  Ghana                   
4  Liberia                 
5  Burkina Faso            
6  Guinea                  
7  Guinea-Bissau           
8  Mali                    
9  Senegal                 
10 Sierra Leone            
11 The Gambia              
12 Djibouti                
13 Eritrea                 
14 Ethiopia                
15 Sudan                   
16 Algeria                 
17 Cameroon                
18 Central African Republic
19 Tunisia                 
20 Benin                   
21 Equatorial Guinea       
22 Niger                   
23 Nigeria                 
24 Togo                    
25 Somalia                 
26 Botswana                
27 Burundi                 
28 Rwanda                  
29 Zambia                  
30 Zimbabwe                
31 Comoros                 
32 Lesotho                 
33 Malawi                  
34 Mozambique              
35 South Africa            
36 Swaziland               
37 Angola                  
38 Congo                   
39 Congo, DRC              
40 Gabon                   
41 Namibia                 
42 Madagascar              
43 Mauritius               
44 Seychelles              
45 Libya                   
46 Chad                    
47 Uganda                  
48 Kenya                   
49 Tanzania                
50 Morocco                 
51 Mauritania              
52 South Sudan

country          
1  DR Congo (Zaire) 
2  Burundi          
3  Nigeria          
4  Sudan            
5  Uganda           
6  Ethiopia         
7  Mozambique       
8  Somalia          
9  Cameroon         
10 Mali             
11 Rwanda           
12 Algeria          
13 Angola           
14 Congo            
15 Eritrea, Ethiopia
16 South Sudan      
17 Libya            
18 Niger            
19 Chad             
20 Kenya            
21 Tunisia

## Let's plan

1. **Filter** = we only need the country name, country id, year and GDP column from the country table. We also only want data from 2015 and onwards, so let's filter for that as well. It's not needed now, but when we have 1.000.000 rows and an old laptop...
1. **Aggregate** = the conflict data to country level, taking the sum of fatalities. This will also filter it for us!
1. **Join** = We use the filtered country table as base. What kind of join do we need?
1. **DONE**

In [50]:
#FILTERING
filtered_country <- select(country, country_name, country_id, year, gdp)
filtered_country <- filter(filtered_country, year>=2015 & year<2019)
filtered_country

country_name  country_id year gdp     
1   Cape Verde    402        2015 1513.00 
2   Cape Verde    402        2016 1561.10 
3   Cape Verde    402        2017 1712.70 
4   Cote d'Ivoire 437        2015 3267.81 
5   Cote d'Ivoire 437        2016 3465.94 
6   Cote d'Ivoire 437        2017 2894.78 
7   Ghana         452        2015 3950.29 
8   Ghana         452        2016 4001.10 
9   Ghana         452        2017 4157.05 
10  Liberia       450        2015  788.56 
11  Liberia       450        2016  756.72 
12  Liberia       450        2017 1009.50 
13  Burkina Faso  439        2015 1558.06 
14  Burkina Faso  439        2016 1602.02 
15  Burkina Faso  439        2017 1512.73 
16  Guinea        438        2015 1189.35 
17  Guinea        438        2016 1220.49 
18  Guinea        438        2017 1271.53 
19  Guinea-Bissau 404        2015 1430.84 
20  Guinea-Bissau 404        2016 1473.04 
21  Guinea-Bissau 404        2017 1660.13 
22  Mali          432        2015 1928.42 
23  Mali          432        2016 1972.12 
24  Mali          432        2017 2275.19 
25  Senegal       433        2015 2308.00 
26  Senegal       433        2016 2392.11 
27  Senegal       433        2017 2455.44 
28  Sierra Leone  451        2015 1322.05 
29  Sierra Leone  451        2016 1372.11 
30  Sierra Leone  451        2017 1788.69 
⋮   ⋮             ⋮          ⋮    ⋮       
127 Seychelles    591        2015 25689.15
128 Seychelles    591        2016 26488.96
129 Seychelles    591        2017 27489.96
130 Libya         620        2015 17793.44
131 Libya         620        2016 17448.03
132 Libya         620        2017 17109.32
133 Chad          483        2015  2057.53
134 Chad          483        2016  1854.71
135 Chad          483        2017  2224.23
136 Uganda        500        2015  1700.50
137 Uganda        500        2016  1721.93
138 Uganda        500        2017  1885.35
139 Kenya         501        2015  2849.92
140 Kenya         501        2016  2940.39
141 Kenya         501        2017  3261.60
142 Tanzania      510        2015  2503.30
143 Tanzania      510        2016  2596.14
144 Tanzania      510        2017  2776.88
145 Morocco       600        2015  7326.71
146 Morocco       600        2016  7306.78
147 Morocco       600        2017  7712.69
148 Mauritania    435        2015  3620.30
149 Mauritania    435        2016  3590.79
150 Mauritania    435        2017  4238.56
151 Sudan         625        2015  4313.11
152 Sudan         625        2016  4408.34
153 Sudan         625        2017  4665.70
154 South Sudan   626        2015  1816.75
155 South Sudan   626        2016       NA
156 South Sudan   626        2017  1829.13

In [18]:
# AGGREGATION
grouped_conflict <- group_by(conflict,country_id,year)
conflicts_in_country <- summarize(grouped_conflict, number_of_conflicts=n(), fatalities=sum(fatalities))
conflicts_in_country

country_id year number_of_conflicts fatalities
1  432        2015 3                    165      
2  432        2016 1                     96      
3  432        2017 2                    345      
4  436        2015 1                    171      
5  436        2016 1                    274      
6  436        2017 1                    203      
7  471        2015 2                    995      
8  471        2016 2                    221      
9  471        2017 1                     63      
10 475        2015 2                   4622      
11 475        2016 2                   2430      
12 475        2017 2                   1879      
13 483        2015 1                    272      
14 483        2017 1                     57      
15 484        2016 1                     51      
16 490        2016 1                    164      
17 490        2017 2                   1698      
18 500        2015 1                    197      
19 500        2016 1                    132      
20 500        2017 1                    235      
21 501        2015 1                     42      
22 501        2016 1                     49      
23 501        2017 1                     85      
24 516        2015 1                    133      
25 517        2016 1                    129      
26 520        2015 1                   1178      
27 520        2016 1                   1925      
28 520        2017 1                   1837      
29 530        2015 2                     50      
30 530        2016 2                     50      
31 531        2016 1                     25      
32 540        2017 1                     25      
33 541        2016 1                     26      
34 615        2015 2                    110      
35 615        2016 1                     86      
36 615        2017 1                     60      
37 616        2016 1                     72      
38 620        2015 2                    274      
39 620        2016 1                   1678      
40 620        2017 2                    404      
41 625        2015 1                   1264      
42 625        2016 1                   1314      
43 625        2017 1                    128      
44 626        2015 1                    493      
45 626        2016 1                    735      
46 626        2017 1                    465

In [19]:
final_dataset <- left_join(filtered_country, conflicts_in_country, by=c('country_id','year'))
final_dataset


country_name  country_id year gdp      number_of_conflicts fatalities
1   Cape Verde    402        2015 1513.00  NA                   NA       
2   Cape Verde    402        2016 1561.10  NA                   NA       
3   Cape Verde    402        2017 1712.70  NA                   NA       
4   Cote d'Ivoire 437        2015 3267.81  NA                   NA       
5   Cote d'Ivoire 437        2016 3465.94  NA                   NA       
6   Cote d'Ivoire 437        2017 2894.78  NA                   NA       
7   Ghana         452        2015 3950.29  NA                   NA       
8   Ghana         452        2016 4001.10  NA                   NA       
9   Ghana         452        2017 4157.05  NA                   NA       
10  Liberia       450        2015  788.56  NA                   NA       
11  Liberia       450        2016  756.72  NA                   NA       
12  Liberia       450        2017 1009.50  NA                   NA       
13  Burkina Faso  439        2015 1558.06  NA                   NA       
14  Burkina Faso  439        2016 1602.02  NA                   NA       
15  Burkina Faso  439        2017 1512.73  NA                   NA       
16  Guinea        438        2015 1189.35  NA                   NA       
17  Guinea        438        2016 1220.49  NA                   NA       
18  Guinea        438        2017 1271.53  NA                   NA       
19  Guinea-Bissau 404        2015 1430.84  NA                   NA       
20  Guinea-Bissau 404        2016 1473.04  NA                   NA       
21  Guinea-Bissau 404        2017 1660.13  NA                   NA       
22  Mali          432        2015 1928.42   3                  165       
23  Mali          432        2016 1972.12   1                   96       
24  Mali          432        2017 2275.19   2                  345       
25  Senegal       433        2015 2308.00  NA                   NA       
26  Senegal       433        2016 2392.11  NA                   NA       
27  Senegal       433        2017 2455.44  NA                   NA       
28  Sierra Leone  451        2015 1322.05  NA                   NA       
29  Sierra Leone  451        2016 1372.11  NA                   NA       
30  Sierra Leone  451        2017 1788.69  NA                   NA       
⋮   ⋮             ⋮          ⋮    ⋮        ⋮                   ⋮         
127 Seychelles    591        2015 25689.15 NA                    NA      
128 Seychelles    591        2016 26488.96 NA                    NA      
129 Seychelles    591        2017 27489.96 NA                    NA      
130 Libya         620        2015 17793.44  2                   274      
131 Libya         620        2016 17448.03  1                  1678      
132 Libya         620        2017 17109.32  2                   404      
133 Chad          483        2015  2057.53  1                   272      
134 Chad          483        2016  1854.71 NA                    NA      
135 Chad          483        2017  2224.23  1                    57      
136 Uganda        500        2015  1700.50  1                   197      
137 Uganda        500        2016  1721.93  1                   132      
138 Uganda        500        2017  1885.35  1                   235      
139 Kenya         501        2015  2849.92  1                    42      
140 Kenya         501        2016  2940.39  1                    49      
141 Kenya         501        2017  3261.60  1                    85      
142 Tanzania      510        2015  2503.30 NA                    NA      
143 Tanzania      510        2016  2596.14 NA                    NA      
144 Tanzania      510        2017  2776.88 NA                    NA      
145 Morocco       600        2015  7326.71 NA                    NA      
146 Morocco       600        2016  7306.78 NA                    NA      
147 Morocco       600        2017  7712.69 NA                    NA      
148 Mauritania    435        2015  3620.30 NA                    NA      
149 Maur

But what if the columns in A and B don't match by name before joining
We actually need to rename these!

We use dplyr's `rename()`. Let's try it here instead 

I don't like `number_of_conflicts` as a column name, I would prefer `count_conflicts` instead. Shorter!

In [20]:
final_data_renamed <- rename(final_dataset, count_conflicts = number_of_conflicts)
final_data_renamed

country_name  country_id year gdp      count_conflicts fatalities
1   Cape Verde    402        2015 1513.00  NA               NA       
2   Cape Verde    402        2016 1561.10  NA               NA       
3   Cape Verde    402        2017 1712.70  NA               NA       
4   Cote d'Ivoire 437        2015 3267.81  NA               NA       
5   Cote d'Ivoire 437        2016 3465.94  NA               NA       
6   Cote d'Ivoire 437        2017 2894.78  NA               NA       
7   Ghana         452        2015 3950.29  NA               NA       
8   Ghana         452        2016 4001.10  NA               NA       
9   Ghana         452        2017 4157.05  NA               NA       
10  Liberia       450        2015  788.56  NA               NA       
11  Liberia       450        2016  756.72  NA               NA       
12  Liberia       450        2017 1009.50  NA               NA       
13  Burkina Faso  439        2015 1558.06  NA               NA       
14  Burkina Faso  439        2016 1602.02  NA               NA       
15  Burkina Faso  439        2017 1512.73  NA               NA       
16  Guinea        438        2015 1189.35  NA               NA       
17  Guinea        438        2016 1220.49  NA               NA       
18  Guinea        438        2017 1271.53  NA               NA       
19  Guinea-Bissau 404        2015 1430.84  NA               NA       
20  Guinea-Bissau 404        2016 1473.04  NA               NA       
21  Guinea-Bissau 404        2017 1660.13  NA               NA       
22  Mali          432        2015 1928.42   3              165       
23  Mali          432        2016 1972.12   1               96       
24  Mali          432        2017 2275.19   2              345       
25  Senegal       433        2015 2308.00  NA               NA       
26  Senegal       433        2016 2392.11  NA               NA       
27  Senegal       433        2017 2455.44  NA               NA       
28  Sierra Leone  451        2015 1322.05  NA               NA       
29  Sierra Leone  451        2016 1372.11  NA               NA       
30  Sierra Leone  451        2017 1788.69  NA               NA       
⋮   ⋮             ⋮          ⋮    ⋮        ⋮               ⋮         
127 Seychelles    591        2015 25689.15 NA                NA      
128 Seychelles    591        2016 26488.96 NA                NA      
129 Seychelles    591        2017 27489.96 NA                NA      
130 Libya         620        2015 17793.44  2               274      
131 Libya         620        2016 17448.03  1              1678      
132 Libya         620        2017 17109.32  2               404      
133 Chad          483        2015  2057.53  1               272      
134 Chad          483        2016  1854.71 NA                NA      
135 Chad          483        2017  2224.23  1                57      
136 Uganda        500        2015  1700.50  1               197      
137 Uganda        500        2016  1721.93  1               132      
138 Uganda        500        2017  1885.35  1               235      
139 Kenya         501        2015  2849.92  1                42      
140 Kenya         501        2016  2940.39  1                49      
141 Kenya         501        2017  3261.60  1                85      
142 Tanzania      510        2015  2503.30 NA                NA      
143 Tanzania      510        2016  2596.14 NA                NA      
144 Tanzania      510        2017  2776.88 NA                NA      
145 Morocco       600        2015  7326.71 NA                NA      
146 Morocco       600        2016  7306.78 NA                NA      
147 Morocco       600        2017  7712.69 NA                NA      
148 Mauritania    435        2015  3620.30 NA                NA      
149 Mauritania    435        2016  3590.79 NA                NA      
150 Mauritania    435        2017  4238.56 NA                NA      
151 Sudan         625        2015  4313.11  1              1264      
152 Sudan     

### We're done, right?

### Nope. Look at the conflict columns!

### Let's fix this!

## Let's plan

1. **Fiter** = we only need the country name, country id, year and GDP column from the country table. We also only want data from 2015 and onwards, so let's filter for that as well. It's not needed now, but when we have 1.000.000 rows and an old laptop...
1. **Aggregate** = the conflict data to country level, taking the sum of fatalities. This will also filter it for us!
1. **Join** = We use the filtered country table as base. What kind of join do we need?
1. <font color='red'> **Transform** = Since the conflict table only contained conflicts, countries that did not match have 0 (NO CONFLICTS) and not NA (unknown/unregistered conflicts). We need to fix this. </font>
1. **DONE**

In [21]:
# We need to do this because, 0 is, by default, stored as a real number, i.e. 0.0000000000
# And the column we want to replace is integer, so expects 0.
# This is an R thing. 
zero <- as.integer(0)

really_final <- mutate(final_data_renamed, 
                       count_conflicts=coalesce(count_conflicts,zero),
                       fatalities=coalesce(fatalities,zero))

arrange(really_final,country_id,year)

country_name      country_id year gdp      count_conflicts fatalities
1   Cape Verde        402        2015  1513.00 0                 0       
2   Cape Verde        402        2016  1561.10 0                 0       
3   Cape Verde        402        2017  1712.70 0                 0       
4   Guinea-Bissau     404        2015  1430.84 0                 0       
5   Guinea-Bissau     404        2016  1473.04 0                 0       
6   Guinea-Bissau     404        2017  1660.13 0                 0       
7   Equatorial Guinea 411        2015 27414.16 0                 0       
8   Equatorial Guinea 411        2016 23822.54 0                 0       
9   Equatorial Guinea 411        2017 33837.77 0                 0       
10  The Gambia        420        2015  1595.62 0                 0       
11  The Gambia        420        2016  1573.09 0                 0       
12  The Gambia        420        2017  1935.93 0                 0       
13  Mali              432        2015  1928.42 3               165       
14  Mali              432        2016  1972.12 1                96       
15  Mali              432        2017  2275.19 2               345       
16  Senegal           433        2015  2308.00 0                 0       
17  Senegal           433        2016  2392.11 0                 0       
18  Senegal           433        2017  2455.44 0                 0       
19  Benin             434        2015  1996.73 0                 0       
20  Benin             434        2016  2019.64 0                 0       
21  Benin             434        2017  2005.93 0                 0       
22  Mauritania        435        2015  3620.30 0                 0       
23  Mauritania        435        2016  3590.79 0                 0       
24  Mauritania        435        2017  4238.56 0                 0       
25  Niger             436        2015   901.36 1               171       
26  Niger             436        2016   910.90 1               274       
27  Niger             436        2017   953.72 1               203       
28  Cote d'Ivoire     437        2015  3267.81 0                 0       
29  Cote d'Ivoire     437        2016  3465.94 0                 0       
30  Cote d'Ivoire     437        2017  2894.78 0                 0       
⋮   ⋮                 ⋮          ⋮    ⋮        ⋮               ⋮         
127 Madagascar        580        2015  1382.63 0                  0      
128 Madagascar        580        2016  1402.49 0                  0      
129 Madagascar        580        2017  1536.87 0                  0      
130 Comoros           581        2015  1419.55 0                  0      
131 Comoros           581        2016  1417.63 0                  0      
132 Comoros           581        2017  1491.96 0                  0      
133 Mauritius         590        2015 18981.82 0                  0      
134 Mauritius         590        2016 19671.07 0                  0      
135 Mauritius         590        2017 18561.58 0                  0      
136 Seychelles        591        2015 25689.15 0                  0      
137 Seychelles        591        2016 26488.96 0                  0      
138 Seychelles        591        2017 27489.96 0                  0      
139 Morocco           600        2015  7326.71 0                  0      
140 Morocco           600        2016  7306.78 0                  0      
141 Morocco           600        2017  7712.69 0                  0      
142 Algeria           615        2015 13807.18 2                110      
143 Algeria           615        2016 14059.21 1                 86      
144 Algeria           615        2017 14353.67 1                 60      
145 Tunisia           616        2015 10813.10 0                  0      
146 Tunisia           616        2016 10815.27 1                 72      
147 Tunisia           616        2017 12003.94 0                  0      
148 Libya             620        2015 17793.44 2                274      
149 Liby

### But I asked the prof. and the prof. said that I shouldn't use GDP, I should instead use the logarithm of GDP!

In [29]:
with_logs <- mutate(really_final, log_gdp=log(gdp+1))
with_logs

# Always add +1 when doing logs. Why? Because log(0) does not exist, but log(1)=0!

country_name  country_id year gdp      count_conflicts fatalities log_gdp  
1   Cape Verde    402        2015 1513.00  0                 0        7.322510 
2   Cape Verde    402        2016 1561.10  0                 0        7.353786 
3   Cape Verde    402        2017 1712.70  0                 0        7.446410 
4   Cote d'Ivoire 437        2015 3267.81  0                 0        8.092181 
5   Cote d'Ivoire 437        2016 3465.94  0                 0        8.151028 
6   Cote d'Ivoire 437        2017 2894.78  0                 0        7.971010 
7   Ghana         452        2015 3950.29  0                 0        8.281797 
8   Ghana         452        2016 4001.10  0                 0        8.294575 
9   Ghana         452        2017 4157.05  0                 0        8.332801 
10  Liberia       450        2015  788.56  0                 0        6.671476 
11  Liberia       450        2016  756.72  0                 0        6.630314 
12  Liberia       450        2017 1009.50  0                 0        6.918201 
13  Burkina Faso  439        2015 1558.06  0                 0        7.351838 
14  Burkina Faso  439        2016 1602.02  0                 0        7.379645 
15  Burkina Faso  439        2017 1512.73  0                 0        7.322332 
16  Guinea        438        2015 1189.35  0                 0        7.082003 
17  Guinea        438        2016 1220.49  0                 0        7.107827 
18  Guinea        438        2017 1271.53  0                 0        7.148762 
19  Guinea-Bissau 404        2015 1430.84  0                 0        7.266716 
20  Guinea-Bissau 404        2016 1473.04  0                 0        7.295762 
21  Guinea-Bissau 404        2017 1660.13  0                 0        7.415253 
22  Mali          432        2015 1928.42  3               165        7.564975 
23  Mali          432        2016 1972.12  1                96        7.587371 
24  Mali          432        2017 2275.19  2               345        7.730258 
25  Senegal       433        2015 2308.00  0                 0        7.744570 
26  Senegal       433        2016 2392.11  0                 0        7.780349 
27  Senegal       433        2017 2455.44  0                 0        7.806468 
28  Sierra Leone  451        2015 1322.05  0                 0        7.187695 
29  Sierra Leone  451        2016 1372.11  0                 0        7.224834 
30  Sierra Leone  451        2017 1788.69  0                 0        7.489798 
⋮   ⋮             ⋮          ⋮    ⋮        ⋮               ⋮          ⋮        
127 Seychelles    591        2015 25689.15 0                  0       10.153863
128 Seychelles    591        2016 26488.96 0                  0       10.184521
129 Seychelles    591        2017 27489.96 0                  0       10.221613
130 Libya         620        2015 17793.44 2                274        9.786641
131 Libya         620        2016 17448.03 1               1678        9.767039
132 Libya         620        2017 17109.32 2                404        9.747437
133 Chad          483        2015  2057.53 1                272        7.629747
134 Chad          483        2016  1854.71 0                  0        7.526023
135 Chad          483        2017  2224.23 1                 57        7.707616
136 Uganda        500        2015  1700.50 1                197        7.439265
137 Uganda        500        2016  1721.93 1                132        7.451782
138 Uganda        500        2017  1885.35 1                235        7.542399
139 Kenya         501        2015  2849.92 1                 42        7.955397
140 Kenya         501        2016  2940.39 1                 49        7.986638
141 Kenya         501        2017  3261.60 1                 85        8.090280
142 Tanzania      510        2015  2503.30 0                  0        7.825765
143 Tanzania      510        2016  2596.14 0                  0        7.862166
144 Tanzania      510        2017  2776.88 0                  0        7.929443
145 

### And I asked the prof. and the prof. said that I should also _lag_ GDP
We frequently use lags, because cause->effect relations take time to develop. It's likely that an economic collapse won't trigger conflict immediately, but in a year!. So we use last year's GDP to see if it has an effect on conflict.

In [47]:
with_lags <- really_final %>% arrange(country_name, year) %>% group_by(country_name) %>% mutate(lagged_gdp = lag(gdp))

# OR, if you want it without pipes
with_lags <- arrange(really_final,country_name, year)
with_lags <- group_by(with_lags,country_name)
with_lags <- mutate(with_lags,lagged_gdp = lag(gdp))

with_lags

#Why did we need to arrange the data first?
#Why did we need to group it afterwards?
#Can we compute a change in GDP from past year to current year? How?

country_name             country_id year gdp      count_conflicts
1   Algeria                  615        2015 13807.18 2              
2   Algeria                  615        2016 14059.21 1              
3   Algeria                  615        2017 14353.67 1              
4   Angola                   540        2015  6265.56 0              
5   Angola                   540        2016  6057.95 0              
6   Angola                   540        2017  1563.85 1              
7   Benin                    434        2015  1996.73 0              
8   Benin                    434        2016  2019.64 0              
9   Benin                    434        2017  2005.93 0              
10  Botswana                 571        2015 15450.28 0              
11  Botswana                 571        2016 15608.32 0              
12  Botswana                 571        2017 16987.37 0              
13  Burkina Faso             439        2015  1558.06 0              
14  Burkina Faso             439        2016  1602.02 0              
15  Burkina Faso             439        2017  1512.73 0              
16  Burundi                  516        2015   751.68 1              
17  Burundi                  516        2016   724.18 0              
18  Burundi                  516        2017   824.07 0              
19  Cameroon                 471        2015  3006.36 2              
20  Cameroon                 471        2016  3061.40 2              
21  Cameroon                 471        2017  3096.99 1              
22  Cape Verde               402        2015  1513.00 0              
23  Cape Verde               402        2016  1561.10 0              
24  Cape Verde               402        2017  1712.70 0              
25  Central African Republic 482        2015   628.97 0              
26  Central African Republic 482        2016   650.54 0              
27  Central African Republic 482        2017   780.49 0              
28  Chad                     483        2015  2057.53 1              
29  Chad                     483        2016  1854.71 0              
30  Chad                     483        2017  2224.23 1              
⋮   ⋮                        ⋮          ⋮    ⋮        ⋮              
127 South Sudan              626        2015  1816.75 1              
128 South Sudan              626        2016       NA 1              
129 South Sudan              626        2017  1829.13 1              
130 Sudan                    625        2015  4313.11 1              
131 Sudan                    625        2016  4408.34 1              
132 Sudan                    625        2017  4665.70 1              
133 Swaziland                572        2015  8099.64 0              
134 Swaziland                572        2016  7777.69 0              
135 Swaziland                572        2017  7804.44 0              
136 Tanzania                 510        2015  2503.30 0              
137 Tanzania                 510        2016  2596.14 0              
138 Tanzania                 510        2017  2776.88 0              
139 The Gambia               420        2015  1595.62 0              
140 The Gambia               420        2016  1573.09 0              
141 The Gambia               420        2017  1935.93 0              
142 Togo                     461        2015  1356.98 0              
143 Togo                     461        2016  1388.44 0              
144 Togo                     461        2017  1203.83 0              
145 Tunisia                  616        2015 10813.10 0              
146 Tunisia                  616        2016 10815.27 1              
147 Tunisia                  616        2017 12003.94 0              
148 Uganda                   500        2015  1700.50 1              
149 Uganda                   500        2016  1721.93 1              
150 Uganda                   500        2017  1885.35 1              
151 Zambia                   551        2015  3646.04 0              
152 Zambia    

Sometimes, you want to lag (shift) by more than 1 year in the past. Use `lag(VARIABLE, nL)` where n is the number of rows to go back. 

Example, 
`with_lags <- mutate(with_lags,lagged_gdp = lag(gdp, 10L))`
would lag 10 years, not one.

Sometimes, you want data from the future. This is called a `lead`, and the function is `lead()`. Works the same as `lag()`.

# Advice : Keep your data clean!

## Clean (or _tidy_ in R lingo) means:

## 1. One variable per column
## 2. One observation per row

If you have a country-year dataset containing GDP and Population, each row should be a country-year, and GDP and Population their own columns. Of course, the country name (and identifier) and year should be included.

If this is not the case, you can use `gather()` and `spread()`


In [49]:
#These examples come directly from dplyr(). Why is this NOT CLEAN?
table2

country     year type       count     
1  Afghanistan 1999 cases             745
2  Afghanistan 1999 population   19987071
3  Afghanistan 2000 cases            2666
4  Afghanistan 2000 population   20595360
5  Brazil      1999 cases           37737
6  Brazil      1999 population  172006362
7  Brazil      2000 cases           80488
8  Brazil      2000 population  174504898
9  China       1999 cases          212258
10 China       1999 population 1272915272
11 China       2000 cases          213766
12 China       2000 population 1280428583

In [54]:
#And let's clean it up!
#spread() takes multi-row observations and turns it into a single row with multiple observations
spread(table2, key = type, value = count)

country     year cases  population
1 Afghanistan 1999    745   19987071
2 Afghanistan 2000   2666   20595360
3 Brazil      1999  37737  172006362
4 Brazil      2000  80488  174504898
5 China       1999 212258 1272915272
6 China       2000 213766 1280428583

In [58]:
table4a
#Why is this one not clean?

country     1999   2000  
1 Afghanistan    745   2666
2 Brazil       37737  80488
3 China       212258 213766

In [63]:
#And let's clean it up!
#spread() takes multi-column observations and turns it into a single row with multiple observations
gather(table4a,`1999`, `2000`, key = "year", value = "deaths")

country     year deaths
1 Afghanistan 1999    745
2 Brazil      1999  37737
3 China       1999 212258
4 Afghanistan 2000   2666
5 Brazil      2000  80488
6 China       2000 213766

# Documentation and future help!

## A cheatsheet:

[https://github.com/rstudio/cheatsheets/blob/master/data-transformation.pdf]

## And documentation:
[https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html]

## A whole book on this:
https://r4ds.had.co.nz/

# HOMEWORK!!!!